# Generated by Django 5.1.1 on 2025-12-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AddField(
            model_name='bank',
            name='code',
            field=models.CharField(blank=True, help_text='Optional bank code (e.g., IBBL, SONALI)', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active banks can be selected by users'),
        ),
    ]
