# Generated by Django 5.1.1 on 2025-12-22 17:54

from django.db import migrations
from banks.models import Bank

def assign_default_bank(apps, schema_editor):
    UserBankAccount = apps.get_model('accounts', 'UserBankAccount')
    Transaction = apps.get_model('transactions', 'Transaction')
    
    # Get or create default bank
    bank, created = Bank.objects.get_or_create(name='Default Bank')
    
    # Assign to accounts
    UserBankAccount.objects.filter(bank__isnull=True).update(bank=bank)
    
    # Assign to transactions
    for account in UserBankAccount.objects.all():
        Transaction.objects.filter(account=account, bank__isnull=True).update(bank=account.bank)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbankaccount_bank'),
        ('banks', '0001_initial'),
        ('transactions', '0006_alter_transaction_bank'),
    ]

    operations = [
        migrations.RunPython(assign_default_bank),
    ]
