# Generated by Django 5.1.1 on 2025-12-29 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userbankaccount_branch_userbankaccount_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('Islamic Bank', 'Islamic Bank'), ('Sonali Bank', 'Sonali Bank'), ('Pubali Bank', 'Pubali Bank'), ('Uttara Bank', 'Uttara Bank'), ('Other', 'Other')], max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Bank Account',
                'verbose_name_plural': 'External Bank Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
