# Generated by Django 5.1.1 on 2025-12-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_unique_constraint_externalbankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalbankaccount',
            options={'ordering': ['-date_added'], 'verbose_name': 'External Bank Account', 'verbose_name_plural': 'External Bank Accounts'},
        ),
        migrations.AddField(
            model_name='externalbankaccount',
            name='account_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='externalbankaccount',
            name='branch_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='externalbankaccount',
            name='date_added',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
