# Generated by Django 5.1.1 on 2025-12-24 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_loan_loanpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='monthly_installment',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='term_months',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='installment_number',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_purpose',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
