# Generated by Django 5.1.1 on 2025-12-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_loan_due_date_remove_loan_interest_rate_and_more'),
    ]

    operations = [
    ]
