# Generated by Django 5.1.1 on 2025-12-24 17:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_rename_loanpayment_user_to_payer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-applied_date']},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_incoming',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='transactions.loan'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
