# Generated by Django 5.1.1 on 2025-12-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_add_transaction_type_and_is_incoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.loan'),
        ),
    ]
