# Generated by Django 5.1.1 on 2025-12-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_externalbankaccount_options_and_more'),
        ('transactions', '0016_alter_loanpayment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.externalbankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_balance_after_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Transfer'), (6, 'External Withdrawal'), (7, 'External Transfer')], null=True),
        ),
    ]
