# Generated by Django 5.1.1 on 2025-12-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchchangerequest',
            name='current_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_requests', to='branch_management.branch'),
        ),
    ]
